// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ayah/{id}": {
            "get": {
                "description": "Get a specific ayah by its global ID (1-6236)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ayah"
                ],
                "summary": "Get ayah by global ID",
                "parameters": [
                    {
                        "maximum": 6236,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Global ayah ID (1-6236)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AyahDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/healthcheck.HealthCheck"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Check if the API is ready to serve requests (database connectivity)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/healthcheck.HealthCheck"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/juz": {
            "get": {
                "description": "Get a list of all 30 juz (parts) of the Quran",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Juz"
                ],
                "summary": "List all juz",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/juz.Juz"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/juz/{number}": {
            "get": {
                "description": "Get detailed information about a specific juz",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Juz"
                ],
                "summary": "Get juz by number",
                "parameters": [
                    {
                        "maximum": 30,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Juz number (1-30)",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/juz.Juz"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/juz/{number}/ayah": {
            "get": {
                "description": "Get all ayahs from a specific juz with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Juz"
                ],
                "summary": "Get ayahs by juz",
                "parameters": [
                    {
                        "maximum": 30,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Juz number (1-30)",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.JuzAyahsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/juz/{number}/surah": {
            "get": {
                "description": "Get all surahs that appear in a specific juz",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Juz"
                ],
                "summary": "Get surahs by juz",
                "parameters": [
                    {
                        "maximum": 30,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Juz number (1-30)",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/juz.JuzSurah"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/random": {
            "get": {
                "description": "Get a random ayah, optionally filtered by surah",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ayah"
                ],
                "summary": "Get random ayah",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Filter by surah ID (0 = any)",
                        "name": "surah_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AyahDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sajda": {
            "get": {
                "description": "Get all 15 sajda tilawah ayahs in the Quran",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ayah"
                ],
                "summary": "List sajda ayahs",
                "parameters": [
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.SajdaListItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Full-text search across Quran ayahs (Arabic, Indonesian, English) using FTS5",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search ayahs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "maximum": 114,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Filter by surah ID",
                        "name": "surah_id",
                        "in": "query"
                    },
                    {
                        "maximum": 30,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Filter by juz number",
                        "name": "juz",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.SearchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/surah": {
            "get": {
                "description": "Get a list of all 114 surahs, optionally filtered by revelation type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Surah"
                ],
                "summary": "List all surahs",
                "parameters": [
                    {
                        "enum": [
                            "meccan",
                            "medinan"
                        ],
                        "type": "string",
                        "description": "Filter by revelation type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/surah.Surah"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/surah/{id}": {
            "get": {
                "description": "Get detailed information about a specific surah",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Surah"
                ],
                "summary": "Get surah by ID",
                "parameters": [
                    {
                        "maximum": 114,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Surah ID (1-114)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/surah.Surah"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/surah/{id}/ayah": {
            "get": {
                "description": "Get ayahs from a specific surah with optional range filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ayah"
                ],
                "summary": "Get ayahs by surah",
                "parameters": [
                    {
                        "maximum": 114,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Surah ID (1-114)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Start ayah number (must use with 'to')",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "End ayah number (must use with 'from')",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.SurahAyahsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/surah/{id}/ayah/{number}": {
            "get": {
                "description": "Get a specific ayah by its surah ID and number within that surah",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ayah"
                ],
                "summary": "Get ayah by surah and number",
                "parameters": [
                    {
                        "maximum": 114,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Surah ID (1-114)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Ayah number within the surah",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "id",
                            "en"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Translation language",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AyahDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AyahDetailResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "juz": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                },
                "number_in_surah": {
                    "type": "integer"
                },
                "revelation_type": {
                    "type": "string"
                },
                "sajda": {
                    "type": "string"
                },
                "surah_id": {
                    "type": "integer"
                },
                "surah_info": {
                    "$ref": "#/definitions/handler.AyahDetailSurahInfo"
                },
                "text_uthmani": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                }
            }
        },
        "handler.AyahDetailSurahInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_latin": {
                    "type": "string"
                }
            }
        },
        "handler.AyahListItem": {
            "type": "object",
            "properties": {
                "juz": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                },
                "number_in_surah": {
                    "type": "integer"
                },
                "sajda": {
                    "type": "string"
                },
                "text_uthmani": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                }
            }
        },
        "handler.JuzAyahListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "juz_number": {
                    "type": "integer"
                },
                "number_in_surah": {
                    "type": "integer"
                },
                "surah_id": {
                    "type": "integer"
                },
                "surah_name": {
                    "type": "string"
                },
                "text_uthmani": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                }
            }
        },
        "handler.JuzAyahsResponse": {
            "type": "object",
            "properties": {
                "ayahs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.JuzAyahListItem"
                    }
                },
                "juz": {
                    "$ref": "#/definitions/handler.JuzInfo"
                }
            }
        },
        "handler.JuzInfo": {
            "type": "object",
            "properties": {
                "juz_number": {
                    "type": "integer"
                },
                "total_ayahs": {
                    "type": "integer"
                }
            }
        },
        "handler.SajdaListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "juz": {
                    "type": "integer"
                },
                "number_in_surah": {
                    "type": "integer"
                },
                "sajda_type": {
                    "type": "string"
                },
                "surah_id": {
                    "type": "integer"
                },
                "surah_name": {
                    "type": "string"
                },
                "text_uthmani": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                }
            }
        },
        "handler.SearchResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.Result"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.SurahAyahsResponse": {
            "type": "object",
            "properties": {
                "ayahs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.AyahListItem"
                    }
                },
                "surah": {
                    "$ref": "#/definitions/handler.SurahSummaryResponse"
                }
            }
        },
        "handler.SurahSummaryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_latin": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "healthcheck.HealthCheck": {
            "type": "object",
            "properties": {
                "db_status": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "juz.Juz": {
            "type": "object",
            "properties": {
                "first_ayah_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "juz_number": {
                    "type": "integer"
                },
                "last_ayah_id": {
                    "type": "integer"
                },
                "total_ayahs": {
                    "type": "integer"
                }
            }
        },
        "juz.JuzSurah": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_arabic": {
                    "type": "string"
                },
                "name_latin": {
                    "type": "string"
                },
                "name_transliteration": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "number_of_ayahs": {
                    "type": "integer"
                },
                "revelation_type": {
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not found"
                },
                "error": {
                    "type": "string",
                    "example": "resource not found"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "search.Result": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "juz_number": {
                    "type": "integer"
                },
                "number_in_surah": {
                    "type": "integer"
                },
                "surah_id": {
                    "type": "integer"
                },
                "surah_info": {
                    "$ref": "#/definitions/search.SurahInfo"
                },
                "text_uthmani": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                }
            }
        },
        "search.SurahInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_latin": {
                    "type": "string"
                }
            }
        },
        "surah.Surah": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_arabic": {
                    "type": "string"
                },
                "name_latin": {
                    "type": "string"
                },
                "name_transliteration": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "number_of_ayahs": {
                    "type": "integer"
                },
                "revelation_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Quran API Go",
	Description:      "Internal RESTful API serving Al-Quran data (Arabic text, Indonesian & English translations) for the Ilmunara super app.\n\n---\n\n## MCP Server\n\nAPI ini dilengkapi dengan **MCP (Model Context Protocol) server** sehingga bisa digunakan langsung dari AI assistant seperti Claude, Cursor, dan tools lainnya.\n\n### Koneksi\n\n| | |\n|---|---|\n| **URL** | `https://quran.api.digitalislami.id/mcp` |\n| **Transport** | Streamable HTTP |\n| **Mode** | Stateless (tidak perlu session) |\n\n### Setup Claude Desktop\n\nTambahkan ke file `claude_desktop_config.json`:\n\n```json\n{\n\"mcpServers\": {\n\"quran\": {\n\"type\": \"http\",\n\"url\": \"https://quran.api.digitalislami.id/mcp\"\n}\n}\n}\n```\n\n### Tools yang Tersedia\n\n| Tool | Deskripsi |\n|---|---|\n| `list_surahs` | Daftar semua 114 surah |\n| `get_surah` | Detail surah berdasarkan ID |\n| `get_ayahs_by_surah` | Ayat-ayat dalam surah tertentu |\n| `get_ayah` | Ayat berdasarkan ID global |\n| `get_ayah_by_ref` | Ayat berdasarkan nomor surah dan ayat |\n| `random_ayah` | Ayat acak |\n| `list_juz` | Daftar semua 30 juz |\n| `get_juz` | Detail juz tertentu |\n| `get_ayahs_by_juz` | Ayat-ayat dalam juz tertentu |\n| `search_quran` | Pencarian full-text (Arab, Indonesia, Inggris) |\n\n### Contoh Penggunaan\n\nSetelah terhubung, kamu bisa langsung tanya ke AI:\n\n> *\"Tampilkan ayat pertama surah Al-Baqarah beserta terjemahannya\"*\n\n> *\"Cari ayat yang mengandung kata 'sabar' dalam terjemahan Indonesia\"*\n\n> *\"Surah apa saja yang ada di Juz 30?\"*",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
